#!/bin/bash

VERSION=0.2.2
APPNAME=annona_bot
APPGITUSER=AnnonaOrg
echo ${APPNAME}
echo "package constvar" > ./core/constvar/version.go
echo "const(APP_NAME = \"${APPNAME}\"" >> ./core/constvar/version.go
echo "APP_VERSION = \"${VERSION}\")" >> ./core/constvar/version.go
go fmt ./core/constvar

rm ./cmd/annona_bot/annona_bot
#git init #
git add .
git commit -m "v${VERSION} debug"
#git remote add github git@github.com:${APPGITUSER}/${APPNAME}.git #
#git branch -M main #
git push -u origin main

git tag "v${VERSION}"
git push --tags  -u origin main
## git remote -v